package es.oposicionapp;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.UUID;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.postgresql.util.PSQLException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.CannotGetJdbcConnectionException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.Container.ExecResult;
import org.testcontainers.images.builder.Transferable;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

@Testcontainers
@SpringBootTest(properties = {
		"spring.jpa.hibernate.ddl-auto=validate",
		"spring.jpa.open-in-view=false"
})
class OposicionAppApplicationTests {

	@Container
	static PostgreSQLContainer postgres = new PostgreSQLContainer("postgres:18");

	static String appPassword = UUID.randomUUID().toString();

	static String migratorPassword = UUID.randomUUID().toString();

	@DynamicPropertySource
	static void configurePostgres(DynamicPropertyRegistry registry) {
		postgres.start();
		bootstrapRoles(postgres);
		setRolePasswords(postgres, appPassword, migratorPassword);

		registry.add("spring.datasource.url", postgres::getJdbcUrl);
		registry.add("spring.datasource.username", () -> "oposicionapp_app");
		registry.add("spring.datasource.password", () -> appPassword);
		registry.add("spring.flyway.user", () -> "oposicionapp_migrator");
		registry.add("spring.flyway.password", () -> migratorPassword);
	}

	@Autowired
	JdbcTemplate jdbcTemplate;

	@Test
	void contextLoads() {
	}

	@Test
	void flywayCreatesInitialSchemas() {
		assertThat(schemaExists("core")).isTrue();
		assertThat(schemaExists("c1_tai")).isTrue();
		assertThat(schemaExists("study")).isTrue();

		Integer installedRank = jdbcTemplateForRole(postgres, "oposicionapp_migrator", migratorPassword).queryForObject(
				"select installed_rank from flyway_schema_history where version = '1' and success = true",
				Integer.class);

		assertThat(installedRank).isNotNull();
	}

	@Test
	void applicationRoleCanUseDataButCannotChangeStructure() {
		JdbcTemplate migratorJdbcTemplate = jdbcTemplateForRole(
				postgres,
				"oposicionapp_migrator",
				migratorPassword);

		migratorJdbcTemplate.execute(
				"create table core.permission_probe (id integer generated by default as identity primary key, label text not null)");

		jdbcTemplate.update("insert into core.permission_probe (label) values (?)", "probe");
		assertThat(jdbcTemplate.queryForObject("select label from core.permission_probe where id = 1", String.class))
				.isEqualTo("probe");

		jdbcTemplate.update("update core.permission_probe set label = ? where id = 1", "updated");
		jdbcTemplate.update("delete from core.permission_probe where id = 1");

		assertThatThrownBy(() -> jdbcTemplate.execute("create table core.app_forbidden (id integer)"))
				.satisfies(throwable -> assertSqlState(throwable, "42501"));
		assertThatThrownBy(() -> jdbcTemplate.execute("drop table core.permission_probe"))
				.satisfies(throwable -> assertSqlState(throwable, "42501"));

		migratorJdbcTemplate.execute("drop table core.permission_probe");
	}

	@Test
	void databaseRolesDoNotHaveAdministrativePrivileges() {
		assertThat(roleAdminFlags("oposicionapp_app")).containsExactly(false, false, false, false, false);
		assertThat(roleAdminFlags("oposicionapp_migrator")).containsExactly(false, false, false, false, false);
		assertThat(schemaCreatePrivilege("oposicionapp_app", "public")).isFalse();
		assertThat(roleMemberships("oposicionapp_app")).isZero();
		assertThat(roleMemberships("oposicionapp_migrator")).isZero();
	}

	@Test
	void bootstrapSupportsDatabaseWithExistingV1AppliedByPostgres() {
		try (PostgreSQLContainer existingDatabase = new PostgreSQLContainer("postgres:18")) {
			existingDatabase.start();

			Flyway.configure()
					.dataSource(existingDatabase.getJdbcUrl(), existingDatabase.getUsername(), existingDatabase.getPassword())
					.locations("classpath:db/migration")
					.load()
					.migrate();

			JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
					existingDatabase,
					existingDatabase.getUsername(),
					existingDatabase.getPassword());
			adminJdbcTemplate.execute("create table core.existing_probe (id integer primary key, label text not null)");
			adminJdbcTemplate.update("insert into core.existing_probe (id, label) values (1, 'kept')");
			Map<String, Object> originalHistory = flywayHistory(existingDatabase);

			String existingAppPassword = UUID.randomUUID().toString();
			String existingMigratorPassword = UUID.randomUUID().toString();
			bootstrapRoles(existingDatabase);
			setRolePasswords(existingDatabase, existingAppPassword, existingMigratorPassword);

			Flyway.configure()
					.dataSource(existingDatabase.getJdbcUrl(), "oposicionapp_migrator", existingMigratorPassword)
					.locations("classpath:db/migration")
					.load()
					.migrate();

			JdbcTemplate existingAppJdbcTemplate = jdbcTemplateForRole(
					existingDatabase,
					"oposicionapp_app",
					existingAppPassword);
			JdbcTemplate existingMigratorJdbcTemplate = jdbcTemplateForRole(
					existingDatabase,
					"oposicionapp_migrator",
					existingMigratorPassword);

			bootstrapRoles(existingDatabase);

			assertThat(existingAppJdbcTemplate.queryForObject("select count(*) from core.existing_probe", Integer.class))
					.isEqualTo(1);
			assertThat(existingAppJdbcTemplate.queryForObject("select label from core.existing_probe where id = 1", String.class))
					.isEqualTo("kept");
			assertThat(flywayHistory(existingDatabase)).containsAllEntriesOf(originalHistory);
			assertThat(schemaCreatePrivilege(existingDatabase, "oposicionapp_migrator", "public")).isFalse();
			assertThat(existingMigratorJdbcTemplate.queryForObject(
					"select tableowner from pg_tables where schemaname = 'core' and tablename = 'existing_probe'",
					String.class)).isEqualTo("oposicionapp_migrator");
		}
	}

	@Test
	void bootstrapCanBeRepeatedWithoutLosingExistingData() {
		JdbcTemplate migratorJdbcTemplate = jdbcTemplateForRole(
				postgres,
				"oposicionapp_migrator",
				migratorPassword);

		migratorJdbcTemplate.execute("create table core.repeat_probe (id integer primary key, label text not null)");
		jdbcTemplate.update("insert into core.repeat_probe (id, label) values (?, ?)", 1, "kept");

		bootstrapRoles(postgres);

		assertThat(jdbcTemplate.queryForObject("select label from core.repeat_probe where id = 1", String.class))
				.isEqualTo("kept");
		assertThat(schemaCreatePrivilege("oposicionapp_migrator", "public")).isFalse();

		migratorJdbcTemplate.execute("drop table core.repeat_probe");
	}

	@Test
	void bootstrapNormalizesExistingApplicationRolePrivilegesInsideProjectScope() {
		JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
				postgres,
				postgres.getUsername(),
				postgres.getPassword());
		adminJdbcTemplate.execute("grant create on database \"" + postgres.getDatabaseName() + "\" to oposicionapp_app");
		adminJdbcTemplate.execute("grant create on schema core to oposicionapp_app");
		adminJdbcTemplate.execute("grant select on table public.flyway_schema_history to oposicionapp_app");

		bootstrapRoles(postgres);

		assertThat(databaseCreatePrivilege("oposicionapp_app")).isFalse();
		assertThat(schemaCreatePrivilege("oposicionapp_app", "core")).isFalse();
		assertThat(tableSelectPrivilege("oposicionapp_app", "public", "flyway_schema_history")).isFalse();
	}

	@Test
	void bootstrapChangesIndependentCompositeTypeOwnerWithoutTouchingTableRowTypes() {
		JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
				postgres,
				postgres.getUsername(),
				postgres.getPassword());
		adminJdbcTemplate.execute("create type core.address_probe as (street text, number integer)");
		adminJdbcTemplate.execute("create table core.type_probe (id integer primary key)");

		assertThat(typeOwner("core", "address_probe")).isEqualTo(postgres.getUsername());
		assertThat(typeOwner("core", "type_probe")).isEqualTo(postgres.getUsername());

		bootstrapRoles(postgres);
		bootstrapRoles(postgres);

		assertThat(typeOwner("core", "address_probe")).isEqualTo("oposicionapp_migrator");
		assertThat(typeOwner("core", "type_probe")).isEqualTo("oposicionapp_migrator");

		jdbcTemplateForRole(postgres, "oposicionapp_migrator", migratorPassword)
				.execute("drop table core.type_probe");
		jdbcTemplateForRole(postgres, "oposicionapp_migrator", migratorPassword)
				.execute("drop type core.address_probe");
	}

	@Test
	void bootstrapRejectsDirectPublicPrivilegesOutsideFlywayHistory() {
		try (PostgreSQLContainer conflictingDatabase = new PostgreSQLContainer("postgres:18")) {
			conflictingDatabase.start();
			JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
					conflictingDatabase,
					conflictingDatabase.getUsername(),
					conflictingDatabase.getPassword());
			adminJdbcTemplate.execute("create table public.external_public_table (id integer)");
			adminJdbcTemplate.execute("create role oposicionapp_app login");
			adminJdbcTemplate.execute("grant select on public.external_public_table to oposicionapp_app");

			assertThatThrownBy(() -> bootstrapRoles(conflictingDatabase))
					.hasRootCauseInstanceOf(SQLException.class);
		}
	}

	@Test
	void documentedPsqlInvocationRunsBootstrapWithIdentifierVariable() throws Exception {
		try (PostgreSQLContainer psqlDatabase = new PostgreSQLContainer("postgres:18")) {
			psqlDatabase.start();
			psqlDatabase.copyFileToContainer(
					Transferable.of(readBootstrapSql().getBytes(StandardCharsets.UTF_8)),
					"/tmp/postgresql_roles.sql");

			ExecResult result = psqlDatabase.execInContainer(
					"psql",
					"-U",
					psqlDatabase.getUsername(),
					"-d",
					psqlDatabase.getDatabaseName(),
					"-v",
					"ON_ERROR_STOP=1",
					"-v",
					"POSTGRES_DB=" + psqlDatabase.getDatabaseName(),
					"-f",
					"/tmp/postgresql_roles.sql");

			assertThat(result.getExitCode()).isZero();
			assertThat(roleExists(
					jdbcTemplateForRole(psqlDatabase, psqlDatabase.getUsername(), psqlDatabase.getPassword()),
					"oposicionapp_app")).isTrue();
		}
	}

	@Test
	void migratorKeepsTemporaryPublicCreateUntilAdministrativeFinalization() {
		try (PostgreSQLContainer freshDatabase = new PostgreSQLContainer("postgres:18")) {
			freshDatabase.start();

			String freshMigratorPassword = UUID.randomUUID().toString();
			bootstrapRoles(freshDatabase);
			setRolePasswords(freshDatabase, UUID.randomUUID().toString(), freshMigratorPassword);

			assertThat(schemaCreatePrivilege(freshDatabase, "oposicionapp_migrator", "public")).isTrue();

			Flyway.configure()
					.dataSource(freshDatabase.getJdbcUrl(), "oposicionapp_migrator", freshMigratorPassword)
					.locations("classpath:db/migration")
					.load()
					.migrate();

			assertThat(schemaCreatePrivilege(freshDatabase, "oposicionapp_migrator", "public")).isTrue();

			bootstrapRoles(freshDatabase);

			assertThat(schemaCreatePrivilege(freshDatabase, "oposicionapp_migrator", "public")).isFalse();
		}
	}

	@Test
	void bootstrapRunsTransactionallyAndStopsOnErrors() {
		try (PostgreSQLContainer failingDatabase = new PostgreSQLContainer("postgres:18")) {
			failingDatabase.start();

			String brokenBootstrap = bootstrapSqlFor(failingDatabase)
					.replace(
							"ALTER ROLE oposicionapp_app WITH LOGIN",
							"SELECT 1 / 0;\nALTER ROLE oposicionapp_app WITH LOGIN");

			assertThatThrownBy(() -> executeAdminSql(failingDatabase, brokenBootstrap))
					.hasRootCauseInstanceOf(SQLException.class);

			JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
					failingDatabase,
					failingDatabase.getUsername(),
					failingDatabase.getPassword());
			assertThat(roleExists(adminJdbcTemplate, "oposicionapp_app")).isFalse();
			assertThat(roleExists(adminJdbcTemplate, "oposicionapp_migrator")).isFalse();
		}
	}

	@Test
	void bootstrapRejectsUnexpectedRoleMemberships() {
		try (PostgreSQLContainer conflictingDatabase = new PostgreSQLContainer("postgres:18")) {
			conflictingDatabase.start();
			JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
					conflictingDatabase,
					conflictingDatabase.getUsername(),
					conflictingDatabase.getPassword());
			adminJdbcTemplate.execute("create role external_parent");
			adminJdbcTemplate.execute("create role oposicionapp_app login");
			adminJdbcTemplate.execute("grant external_parent to oposicionapp_app");

			assertThatThrownBy(() -> bootstrapRoles(conflictingDatabase))
					.hasRootCauseInstanceOf(SQLException.class);
		}
	}

	@Test
	void bootstrapRestrictsExistingProjectRoles() {
		try (PostgreSQLContainer existingRolesDatabase = new PostgreSQLContainer("postgres:18")) {
			existingRolesDatabase.start();
			JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
					existingRolesDatabase,
					existingRolesDatabase.getUsername(),
					existingRolesDatabase.getPassword());
			adminJdbcTemplate.execute("create role oposicionapp_app login createdb createrole replication bypassrls");
			adminJdbcTemplate.execute("create role oposicionapp_migrator login createdb createrole replication bypassrls");

			bootstrapRoles(existingRolesDatabase);

			assertThat(roleAdminFlags(existingRolesDatabase, "oposicionapp_app"))
					.containsExactly(false, false, false, false, false);
			assertThat(roleAdminFlags(existingRolesDatabase, "oposicionapp_migrator"))
					.containsExactly(false, false, false, false, false);
		}
	}

	@Test
	void bootstrapRejectsDirectPrivilegesOutsideProjectSchemas() {
		try (PostgreSQLContainer conflictingDatabase = new PostgreSQLContainer("postgres:18")) {
			conflictingDatabase.start();
			JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
					conflictingDatabase,
					conflictingDatabase.getUsername(),
					conflictingDatabase.getPassword());
			adminJdbcTemplate.execute("create schema external_schema");
			adminJdbcTemplate.execute("create table external_schema.external_table (id integer)");
			adminJdbcTemplate.execute("create role oposicionapp_app login");
			adminJdbcTemplate.execute("grant select on external_schema.external_table to oposicionapp_app");

			assertThatThrownBy(() -> bootstrapRoles(conflictingDatabase))
					.hasRootCauseInstanceOf(SQLException.class);
		}
	}

	private boolean schemaExists(String schemaName) {
		Boolean exists = jdbcTemplate.queryForObject(
				"select exists (select 1 from information_schema.schemata where schema_name = ?)",
				Boolean.class,
				schemaName);
		return Boolean.TRUE.equals(exists);
	}

	private Boolean[] roleAdminFlags(String roleName) {
		return roleAdminFlags(postgres, roleName);
	}

	private static Boolean[] roleAdminFlags(PostgreSQLContainer container, String roleName) {
		JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
				container,
				container.getUsername(),
				container.getPassword());
		return adminJdbcTemplate.queryForObject(
				"select rolsuper, rolcreatedb, rolcreaterole, rolreplication, rolbypassrls from pg_roles where rolname = ?",
				(resultSet, rowNumber) -> new Boolean[] {
						resultSet.getBoolean("rolsuper"),
						resultSet.getBoolean("rolcreatedb"),
						resultSet.getBoolean("rolcreaterole"),
						resultSet.getBoolean("rolreplication"),
						resultSet.getBoolean("rolbypassrls")
				},
				roleName);
	}

	private Integer roleMemberships(String roleName) {
		return jdbcTemplate.queryForObject(
				"select count(*) from pg_auth_members membership join pg_roles member on member.oid = membership.member where member.rolname = ?",
				Integer.class,
				roleName);
	}

	private Boolean schemaCreatePrivilege(String roleName, String schemaName) {
		return schemaCreatePrivilege(postgres, roleName, schemaName);
	}

	private Boolean databaseCreatePrivilege(String roleName) {
		return jdbcTemplate.queryForObject(
				"select has_database_privilege(?, current_database(), 'CREATE')",
				Boolean.class,
				roleName);
	}

	private static Boolean schemaCreatePrivilege(PostgreSQLContainer container, String roleName, String schemaName) {
		JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
				container,
				container.getUsername(),
				container.getPassword());
		return adminJdbcTemplate.queryForObject(
				"select has_schema_privilege(?, ?, 'CREATE')",
				Boolean.class,
				roleName,
				schemaName);
	}

	private static Map<String, Object> flywayHistory(PostgreSQLContainer container) {
		JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
				container,
				container.getUsername(),
				container.getPassword());
		return adminJdbcTemplate.queryForMap(
				"select version, description, type, script, checksum, success from flyway_schema_history where version = '1'");
	}

	private Boolean tableSelectPrivilege(String roleName, String schemaName, String tableName) {
		return jdbcTemplate.queryForObject(
				"select has_table_privilege(?, format('%I.%I', ?, ?), 'SELECT')",
				Boolean.class,
				roleName,
				schemaName,
				tableName);
	}

	private String typeOwner(String schemaName, String typeName) {
		return jdbcTemplate.queryForObject(
				"select r.rolname from pg_type t join pg_namespace n on n.oid = t.typnamespace join pg_roles r on r.oid = t.typowner where n.nspname = ? and t.typname = ?",
				String.class,
				schemaName,
				typeName);
	}

	private static boolean roleExists(JdbcTemplate jdbcTemplate, String roleName) {
		Boolean exists = jdbcTemplate.queryForObject(
				"select exists (select 1 from pg_roles where rolname = ?)",
				Boolean.class,
				roleName);
		return Boolean.TRUE.equals(exists);
	}

	private static JdbcTemplate jdbcTemplateForRole(
			PostgreSQLContainer container,
			String username,
			String password) {
		DriverManagerDataSource dataSource = new DriverManagerDataSource();
		dataSource.setUrl(container.getJdbcUrl());
		dataSource.setUsername(username);
		dataSource.setPassword(password);
		return new JdbcTemplate(dataSource);
	}

	private static void bootstrapRoles(PostgreSQLContainer container) {
		executeAdminSql(container, bootstrapSqlFor(container));
	}

	private static void executeAdminSql(PostgreSQLContainer container, String sql) {
		try (var connection = DriverManager.getConnection(
				container.getJdbcUrl(),
				container.getUsername(),
				container.getPassword());
				Statement statement = connection.createStatement()) {
			statement.execute(sql);
		}
		catch (SQLException ex) {
			throw new CannotGetJdbcConnectionException("Could not bootstrap PostgreSQL roles", ex);
		}
	}

	private static String bootstrapSqlFor(PostgreSQLContainer container) {
		return readBootstrapSql()
				.replace(":\"POSTGRES_DB\"", quoteIdentifier(container.getDatabaseName()));
	}

	private static void setRolePasswords(
			PostgreSQLContainer container,
			String appPassword,
			String migratorPassword) {
		JdbcTemplate adminJdbcTemplate = jdbcTemplateForRole(
				container,
				container.getUsername(),
				container.getPassword());
		adminJdbcTemplate.execute("alter role oposicionapp_app with password '" + sqlLiteral(appPassword) + "'");
		adminJdbcTemplate.execute("alter role oposicionapp_migrator with password '" + sqlLiteral(migratorPassword) + "'");
	}

	private static String quoteIdentifier(String identifier) {
		return "\"" + identifier.replace("\"", "\"\"") + "\"";
	}

	private static String sqlLiteral(String value) {
		return value.replace("'", "''");
	}

	private static void assertSqlState(Throwable throwable, String sqlState) {
		Throwable current = throwable;
		while (current != null) {
			if (current instanceof PSQLException psqlException) {
				assertThat(psqlException.getSQLState()).isEqualTo(sqlState);
				return;
			}
			current = current.getCause();
		}
		throw new AssertionError("No PostgreSQL exception found", throwable);
	}

	private static String readBootstrapSql() {
		try (InputStream inputStream = OposicionAppApplicationTests.class.getResourceAsStream(
				"/db/bootstrap/postgresql_roles.sql")) {
			if (inputStream == null) {
				throw new IllegalStateException("Bootstrap SQL not found");
			}
			return new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);
		}
		catch (IOException ex) {
			throw new IllegalStateException("Could not read bootstrap SQL", ex);
		}
	}

}
